### ISSUE TITLE
Vprašanje glede analiziranja podatkov

### ISSUE THREAD

**Issue by jakamrak** [zigagartner/Najvecje-neodvisne-mnozice-z-lokalnim-iskanjem#2]
Pozdravljeni,

lotila sva se analiziranja podatkov. Pri generiranju podatkov (grafov), kjer spreminjamo število vozlišč, se seveda hitro zatakne zaradi počasnosti CLP metode. Zanima naju, če imate kakšen predlog za obravnavo problema v tem primeru. Kljub temu se nama zdi, da je manjše število grafov  (oziroma posledično grafi z manj vozlišči) zadostno, da opazimo vpliv števila vozlišč na velikost maksimalne neodvisne množice in naraščanje časovne zahtevnosti (CLP veliko hitreje kot lokalno in naključni). Pri spreminjanju verjetnosti pa se nama ne zdi smiselno spreminjati le-teh na zelo majhnih intervalih, saj to zelo malo potem vpliva na sam graf in posledično na neodvisne množice in časovno zahtevnost. 

Lokalno iskanje pa še popraviva na zanko while.

Trenutno se vsa koda nahaja v zvezku `koda.ipynb`.
Hvala in lep pozdrav, 

Jaka in Žiga

**Comment by jaanos** [comment]
Če menita, da se vpliv vidi že pri grafih z manjšim številom vozlišč, potem vsekakor ni potrebno poganjati CLP tudi na večjih grafih. Vsekakor pa svetujem, da poganjata lokalno iskanje tudi na nekoliko večjih grafih (dokler pač gre), da potrdita to povezavo.

Kar se tiče spreminjanja verjetnosti pojavitve povezave, lahko svoja opažanja zapišeta v poročilo. Vsekakor bi bilo zanimivo videti, kakšna je zveza med to verjetnostjo in velikostjo največje neodvisne množice - lahko poskusita z vsaj nekaj različnimi verjetnostmi.

**Comment by jakamrak** [comment]
Zdravo.

Bova seveda dodala ugotovitve vezane na različne verjetnosti v poročilo.

Kar se tiče rekurzije pri lokalnem iskanju, sva poskusila zamenjati le-to z while zanko, vendar nama ne uspe popolnoma. Prosila bi, če nama lahko pomagate pri kodi. 
Opazila sva problem pri funkciji lokalnega iskanja. Pri nekaterih parametrih, ko spreminjava verjetnosti, se nama pojavi recursion errror in ne veva zakaj, saj delava tudi na veliko večjih grafih, kjer pa dela brez problema. 

Pri analizi podatkov sva naletela na nekaj, kar si ne znava razložiti. V primeru generiranja 500 $G(50,.03)$ grafov je lokalno iskanje v par primerih občutno boljše od CLP. Ali imate kakšno idejo kaj bi lahko bil razlog. Sliko najdete v `koncno_porocilo.pdf`

le pozdrav,
Jaka in Žiga

**Comment by jakamrak** [comment]
Zdravo @jaanos ,

uspela sva popraviti `lokalno_iskanje` na while. Sedaj so tudi podatki bolj smiselni in zadeva poteka še nekoliko hitreje. Zanima naju, ali je algoritem sedaj ustrezen po popravku rekurzije.

Lp Jaka in Žiga

**Comment by jaanos** [comment]
Opozoril bi na nekaj stvari. Najprej, delata zanke `for` čez sezname, ki jih znotraj njih spreminjata, kar morda ne bo dalo ustreznih rezultatov. Kar zanka v tem primeru počne je to, da najprej obravnava prvi element seznama, potem drugega, itd. Če sta pri tem kak element pobrisala, potem na trenutno mesto skoči naslednji element, kar pomeni, da ga zanka izpusti. Pole tega, ko naredita `I = I + [v1, w1]`, bo v spremenljivki `I` shranjen nov seznam, medtem ko se zanka še vedno sprehaja po starem.

Opozoril bi tudi, da rekurzivni in iterativni algoritem ne počneta istega - tudi nisem prepričan, ali res počneta želeno. Oba za vozlišče `v` v seznamu `I` poiščeta seznam `L` vozlišč, kateri edini sosed v `I` je `v`. Rekurzivni algoritem konča, ko za nek `v` seznam `L` vsebuje največ eno vozlišče - v tem primeru ostane preostanek seznama `I` nepregledan - oziroma gre v rekurzijo z novim seznamom, če najde dve vozlišči, ki ju lahko uporabi namesto `v`. Iterativni algoritem po drugi strani za vsako vozlišče v `I` (glede na zgornje komentarje morda enega izpusti, poleg tega pa ne upošteva na novo dodanih) poskusi poiskati ustrezni vozlišči v `L` (pri čemer dela nepotrebne korake v primeru, da takih vozlišč ni).

Morda bi šlo nekaj takega:
```python
def lokalno_iskanje(G, I):
    I = list(I) # naredimo kopijo seznama I, oziroma ga pretvorimo, če ni v obliki seznama
    J = [] # seznam vozlišč, ki niso bila nadomeščena
    while I: # ponavljamo, dokler seznam ni prazen
        v = I.pop(0) # poberemo prvo vozlišče iz I
        L = [w for w in G.neighbors(v) if tightness(G, I+J, w) == 1]
        it = iter(L) # iterator po L
        for v1 in it:
            for w1 in copy(it): # kopiramo iteratorja - da pregledamo vsak par enkrat
                if w1 not in G.neighbors(v1):
                    I += [v1, w1] # dodamo vozlišči v I
                    break
            else: # notranja zanka je prišla do konca
                continue # poskusimo z drugim v1
            break # notranjo zanko smo prekinili, prekinimo še zunanjo
        else: # zunanja zanka je prišla do konca
            J.append(v) # vozlišča v nismo uspeli nadomestiti, pustimo ga v izhodu
    return J
```
Tukaj vsako vozlišče poskusimo nadomestiti enkrat - vključno s tistimi, ki smo jih našli na novo. Morda bi bilo smiselno celoten postopek ponavljati, dokler še pride do kakega izboljšanja. Lahko pa bi to delala tudi s poskušanjem - namesto, da gresta po vrsti po seznamu `I`, bi lahko izbrala naključno vozlišče in ga poskusila nadomestiti, ter postopek prekinila, ko vama dovoljkrat ne bi uspelo najti ustrezne zamenjave. Tak pristop bi bilo tudi lažje posplošiti na zamenjavo *k* vozlišč s *k*+1 drugimi vozlišči za nek *k* > 1.

**Comment by jakamrak** [comment]
Zdravo,

poskusil sem najin algoritem zamenjati z vašim in še enkrat pognati `koda.ipynb` kjer je celoten program. Pojavi se problem, saj sedaj del, kjer uporabiva tale algoritem na večkrat generiranem G(50,0.3) grafu, stvar ne pride do konca. Pustil sem 10 min potem pa poskusil nastaviti na 10 ponovitev pa CLP reši v 2 sec tale pa sedaj še kar traja kar nama je zelo čudno. Ko kodo skopiram v `testiranje.py`, da preizkusim samo ta algoritem pa mi javi napako na `copy(it)`, češ, da ne mora ustvariti kopije.

Imate morda kakšno idejo kaj bi lahko bilo oziroma, ali bi poskusili pogmati algoritem pri vas na naših podatkih.

Lp Jaka in Žiga

**Comment by jaanos** [comment]
Problem je v tem, da vozlišča `v` ob gradnji seznama `L` ni niti v `I`, niti v `J`, zato bi bilo potrebno izhod funkcije `tightness` primerjati z 0.

Trik s kopiranjem iteratorja očitno ne deluje v starejših različicah Pythona. Glede na to, da iterirata po seznamih, lahko naredita enostavno
```python
        for i, v1 in enumerate(L):
            for w1 in L[i+1:]:
                ...
```

**Comment by zigagartner** [comment]
Pozdravljeni,

najlepša hvala za pomoč. Algoritem sva dopolnila in deluje.

Lep pozdrav,
Žiga in Jaka
